repos:
  # Dart/Flutter formatting and analysis
  - repo: https://github.com/dart-lang/dart_style
    rev: v2.3.4
    hooks:
      - id: dart-format
        args: [--set-exit-if-changed]

  # Dart analyzer
  - repo: https://github.com/dart-lang/dart_analyzer
    rev: v1.0.0
    hooks:
      - id: dart-analyzer
        args: [--fatal-infos, --fatal-warnings]

  # Flutter specific checks
  - repo: https://github.com/flutter/flutter
    rev: stable
    hooks:
      - id: flutter-analyze
        args: [analyze, --no-fatal-infos]

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first

  # YAML validation
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]

  # JSON validation
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types: [json]
        args: [--parser=json]
