[tool.black]
line-length = 88
# Exclude files using a regex pattern
exclude = '''
(
  /(
      \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
    | __pycache__
  )/
)
'''

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "basketball_analytics.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py", "tests_*.py"]
addopts = "-ra -q --ds=basketball_analytics.settings --reuse-db --no-migrations --cov=apps --cov-report=term-missing --cov-report=xml:coverage.xml"

[tool.coverage.run]
branch = true
source = ["apps"]
omit = [
  "*/migrations/*",
  "*/tests/*",
]

[tool.coverage.report]
fail_under = 70
skip_covered = true
show_missing = true