[tool.black]
line-length = 88
# Exclude files using a regex pattern
exclude = '''
(
  /(
      \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
    | __pycache__
  )/
)
'''