# Generated by Django 5.2.5 on 2025-08-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="logo_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
