# Generated by Django 5.2.5 on 2025-08-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jersey_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Jersey Number'),
        ),
    ]
