# Generated by Django 5.2.5 on 2025-08-28 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Possession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time_in_game",
                    models.CharField(
                        max_length=5, verbose_name="Start Time (e.g., 12:00)"
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(verbose_name="Duration (seconds)"),
                ),
                (
                    "quarter",
                    models.IntegerField(
                        choices=[
                            (1, "1st Quarter"),
                            (2, "2nd Quarter"),
                            (3, "3rd Quarter"),
                            (4, "4th Quarter"),
                            (5, "Overtime 1"),
                            (6, "Overtime 2"),
                        ],
                        verbose_name="Quarter",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("MADE_2PT", "Made 2-Point Shot"),
                            ("MISSED_2PT", "Missed 2-Point Shot"),
                            ("MADE_3PT", "Made 3-Point Shot"),
                            ("MISSED_3PT", "Missed 3-Point Shot"),
                            ("MADE_FT", "Made Free Throw(s)"),
                            ("MISSED_FT", "Missed Free Throw(s)"),
                            ("TO_OFFENSIVE_FOUL", "Turnover: Offensive Foul"),
                            ("TO_OUT_OF_BOUNDS", "Turnover: Out of Bounds"),
                            ("TO_TRAVEL", "Turnover: Traveling"),
                            ("TO_SHOT_CLOCK", "Turnover: Shot Clock"),
                            ("TO_8_SECONDS", "Turnover: 8 Seconds"),
                            ("TO_3_SECONDS", "Turnover: 3 Seconds"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Outcome",
                    ),
                ),
                (
                    "offensive_sequence",
                    models.TextField(
                        blank=True,
                        help_text="The sequence of offensive actions, e.g., 'P&R -> Cut -> Kickout Pass'.",
                        verbose_name="Offensive Sequence",
                    ),
                ),
                (
                    "defensive_sequence",
                    models.TextField(
                        blank=True,
                        help_text="The sequence of defensive actions, e.g., 'Hedge -> Switch'.",
                        verbose_name="Defensive Sequence",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="possessions",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
