# Generated by Django 5.2.5 on 2025-08-15 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('possessions', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='possession',
            name='players_on_court',
            field=models.ManyToManyField(related_name='possessions_on_court', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='possession',
            name='team',
            field=models.ForeignKey(help_text='The team that has the possession.', on_delete=django.db.models.deletion.CASCADE, related_name='possessions', to='teams.team'),
        ),
    ]
