# Generated by Django 5.2.5 on 2025-08-17 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0003_playdefinition_parent'),
        ('possessions', '0002_initial'),
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possession',
            name='end_timestamp',
        ),
        migrations.RemoveField(
            model_name='possession',
            name='play_definition',
        ),
        migrations.RemoveField(
            model_name='possession',
            name='players_on_court',
        ),
        migrations.RemoveField(
            model_name='possession',
            name='start_timestamp',
        ),
        migrations.RemoveField(
            model_name='possession',
            name='tracking_data',
        ),
        migrations.AddField(
            model_name='possession',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='How many seconds the possession lasted', verbose_name='Duration (seconds)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='possession',
            name='quarter',
            field=models.IntegerField(choices=[(1, '1st Quarter'), (2, '2nd Quarter'), (3, '3rd Quarter'), (4, '4th Quarter'), (5, 'Overtime 1'), (6, 'Overtime 2')], default=1, verbose_name='Quarter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='possession',
            name='start_time_in_game',
            field=models.CharField(default=0, help_text='The time on the game clock when the possession started, e.g., 12:00', max_length=5, verbose_name='Start Time (e.g., 12:00)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='possession',
            name='outcome',
            field=models.CharField(choices=[('MADE_2PT', 'Made 2-Point Shot'), ('MISSED_2PT', 'Missed 2-Point Shot'), ('MADE_3PT', 'Made 3-Point Shot'), ('MISSED_3PT', 'Missed 3-Point Shot'), ('MADE_FT', 'Made Free Throw(s)'), ('MISSED_FT', 'Missed Free Throw(s)'), ('TO_OFFENSIVE_FOUL', 'Turnover: Offensive Foul'), ('TO_OUT_OF_BOUNDS', 'Turnover: Out of Bounds'), ('TO_TRAVEL', 'Turnover: Traveling'), ('TO_SHOT_CLOCK', 'Turnover: Shot Clock'), ('TO_8_SECONDS', 'Turnover: 8 Seconds'), ('TO_3_SECONDS', 'Turnover: 3 Seconds'), ('OTHER', 'Other')], max_length=50, verbose_name='Outcome'),
        ),
        migrations.AlterField(
            model_name='possession',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possessions', to='teams.team'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField(verbose_name='Action Step')),
                ('play_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executed_actions', to='plays.playdefinition')),
                ('possession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='possessions.possession')),
            ],
            options={
                'ordering': ['possession', 'step'],
            },
        ),
    ]
