# Generated by Django 5.2.5 on 2025-08-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("possessions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="possession",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("MADE_2PTS", "Made 2-Point Shot"),
                    ("MISSED_2PTS", "Missed 2-Point Shot"),
                    ("MADE_3PTS", "Made 3-Point Shot"),
                    ("MISSED_3PTS", "Missed 3-Point Shot"),
                    ("MADE_FT", "Made Free Throw(s)"),
                    ("MISSED_FT", "Missed Free Throw(s)"),
                    ("TO_OFFENSIVE_FOUL", "Turnover: Offensive Foul"),
                    ("TO_OUT_OF_BOUNDS", "Turnover: Out of Bounds"),
                    ("TO_TRAVEL", "Turnover: Traveling"),
                    ("TO_SHOT_CLOCK", "Turnover: Shot Clock"),
                    ("TO_8_SECONDS", "Turnover: 8 Seconds"),
                    ("TO_3_SECONDS", "Turnover: 3 Seconds"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                verbose_name="Outcome",
            ),
        ),
    ]
