# Generated by Django 5.2.5 on 2025-08-17 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0003_playdefinition_parent'),
        ('possessions', '0003_remove_possession_end_timestamp_and_more'),
        ('teams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='possession',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='possession',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_possessions', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='possession',
            name='duration_seconds',
            field=models.PositiveIntegerField(verbose_name='Duration (seconds)'),
        ),
        migrations.AlterField(
            model_name='possession',
            name='start_time_in_game',
            field=models.CharField(max_length=5, verbose_name='Start Time (e.g., 12:00)'),
        ),
        migrations.CreateModel(
            name='PossessionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField(verbose_name='Action Step')),
                ('action_description', models.CharField(help_text="Describes the action, e.g., 'Cut', 'Kickout Pass', or a specific play name.", max_length=255, verbose_name='Action Description')),
                ('play_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_actions', to='plays.playdefinition')),
                ('possession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='possessions.possession')),
            ],
            options={
                'ordering': ['possession', 'step'],
            },
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
