# Generated by Django 5.2.5 on 2025-08-29 16:44

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def set_default_timestamps(apps, schema_editor):
    """Set default timestamps for existing records"""
    Possession = apps.get_model('possessions', 'Possession')
    default_time = timezone.now()
    Possession.objects.filter(created_at__isnull=True).update(created_at=default_time)
    Possession.objects.filter(updated_at__isnull=True).update(updated_at=default_time)


class Migration(migrations.Migration):

    dependencies = [
        ("possessions", "0004_alter_possession_outcome"),
    ]

    operations = [
        # Add new fields with defaults
        migrations.AddField(
            model_name='possession',
            name='points_scored',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='possession',
            name='offensive_set',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('PICK_AND_ROLL', 'Pick and Roll'),
                    ('PICK_AND_POP', 'Pick and Pop'),
                    ('HANDOFF', 'Handoff'),
                    ('BACKDOOR', 'Backdoor'),
                    ('FLARE', 'Flare'),
                    ('DOWN_SCREEN', 'Down Screen'),
                    ('UP_SCREEN', 'Up Screen'),
                    ('CROSS_SCREEN', 'Cross Screen'),
                    ('POST_UP', 'Post Up'),
                    ('ISOLATION', 'Isolation'),
                    ('TRANSITION', 'Transition'),
                    ('OFFENSIVE_REBOUND', 'Offensive Rebound'),
                    ('OTHER', 'Other'),
                ],
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name='possession',
            name='pnr_type',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('BALL_SCREEN', 'Ball Screen'),
                    ('OFF_BALL_SCREEN', 'Off Ball Screen'),
                    ('HANDOFF_SCREEN', 'Handoff Screen'),
                    ('NONE', 'None'),
                ],
                default='NONE',
            ),
        ),
        migrations.AddField(
            model_name='possession',
            name='pnr_result',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('SCORER', 'Scorer'),
                    ('BIG_GUY', 'Big Guy'),
                    ('KICK_OUT', 'Kick Out'),
                    ('REJECT', 'Reject'),
                    ('NONE', 'None'),
                ],
                default='NONE',
            ),
        ),
        migrations.AddField(
            model_name='possession',
            name='has_paint_touch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='possession',
            name='has_kick_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='possession',
            name='has_extra_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='possession',
            name='number_of_passes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='possession',
            name='is_offensive_rebound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='possession',
            name='offensive_rebound_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='possession',
            name='defensive_set',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('MAN_TO_MAN', 'Man to Man'),
                    ('ZONE_2_3', '2-3 Zone'),
                    ('ZONE_3_2', '3-2 Zone'),
                    ('ZONE_1_3_1', '1-3-1 Zone'),
                    ('PRESS', 'Press'),
                    ('TRAP', 'Trap'),
                    ('SWITCH', 'Switch'),
                    ('ICE', 'Ice'),
                    ('GO_OVER', 'Go Over'),
                    ('GO_UNDER', 'Go Under'),
                    ('OTHER', 'Other'),
                ],
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name='possession',
            name='defensive_pnr',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('SWITCH', 'Switch'),
                    ('ICE', 'Ice'),
                    ('GO_OVER', 'Go Over'),
                    ('GO_UNDER', 'Go Under'),
                    ('TRAP', 'Trap'),
                    ('NONE', 'None'),
                ],
                default='NONE',
            ),
        ),
        migrations.AddField(
            model_name='possession',
            name='box_out_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='possession',
            name='offensive_rebounds_allowed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='possession',
            name='shoot_time',
            field=models.PositiveIntegerField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='possession',
            name='shoot_quality',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('EXCELLENT', 'Excellent'),
                    ('GOOD', 'Good'),
                    ('AVERAGE', 'Average'),
                    ('POOR', 'Poor'),
                    ('CONTESTED', 'Contested'),
                    ('OPEN', 'Open'),
                ],
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name='possession',
            name='time_range',
            field=models.CharField(
                max_length=25,
                choices=[
                    ('EARLY_SHOT_CLOCK', 'Early Shot Clock (0-7s)'),
                    ('MID_SHOT_CLOCK', 'Mid Shot Clock (8-14s)'),
                    ('LATE_SHOT_CLOCK', 'Late Shot Clock (15-24s)'),
                    ('SHOT_CLOCK_VIOLATION', 'Shot Clock Violation'),
                ],
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name='possession',
            name='after_timeout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='possession',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='possession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='possession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='possession',
            name='created_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='users.user',
                default=1,  # Assuming user ID 1 exists
            ),
            preserve_default=False,
        ),
        # Add ManyToMany fields
        migrations.AddField(
            model_name='possession',
            name='offensive_rebound_players',
            field=models.ManyToManyField(
                blank=True,
                related_name='offensive_rebounds',
                to='users.user',
            ),
        ),
        migrations.AddField(
            model_name='possession',
            name='players_on_court',
            field=models.ManyToManyField(
                blank=True,
                related_name='possessions_on_court',
                to='users.user',
            ),
        ),
        # Add indexes
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['game', 'quarter'], name='possessions_game_quarte_idx'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['team', 'offensive_set'], name='possessions_team_offen_idx'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['opponent', 'defensive_set'], name='possessions_opponent_idx'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['pnr_type', 'pnr_result'], name='possessions_pnr_type_idx'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['outcome', 'points_scored'], name='possessions_outcome_poi_idx'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['has_paint_touch', 'has_kick_out'], name='possessions_has_paint_idx'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['is_offensive_rebound', 'offensive_rebound_count'], name='possessions_is_offens_idx'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['shoot_quality', 'shoot_time'], name='possessions_shoot_qual_idx'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['after_timeout'], name='possessions_after_tim_idx'),
        ),
    ]
