# Generated by Django 5.2.5 on 2025-08-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possessions', '0004_possession_logged_by_possession_opponent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='possession',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='possession',
            name='defensive_sequence',
            field=models.TextField(blank=True, help_text="The sequence of defensive actions, e.g., 'Hedge -> Switch'.", verbose_name='Defensive Sequence'),
        ),
        migrations.AddField(
            model_name='possession',
            name='offensive_sequence',
            field=models.TextField(blank=True, help_text="The sequence of offensive actions, e.g., 'P&R -> Cut -> Kickout Pass'.", verbose_name='Offensive Sequence'),
        ),
        migrations.DeleteModel(
            name='PossessionAction',
        ),
    ]
