# Generated by Django 5.2.5 on 2025-08-29 16:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("possessions", "0005_auto_20250829_1844"),
        ("teams", "0003_team_logo_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="possession",
            options={"ordering": ["game", "quarter", "start_time_in_game"]},
        ),
        migrations.RenameIndex(
            model_name="possession",
            new_name="possessions_game_id_da365d_idx",
            old_name="possessions_game_quarte_idx",
        ),
        migrations.RenameIndex(
            model_name="possession",
            new_name="possessions_team_id_8ca77a_idx",
            old_name="possessions_team_offen_idx",
        ),
        migrations.RenameIndex(
            model_name="possession",
            new_name="possessions_opponen_59fa7d_idx",
            old_name="possessions_opponent_idx",
        ),
        migrations.RenameIndex(
            model_name="possession",
            new_name="possessions_pnr_typ_358659_idx",
            old_name="possessions_pnr_type_idx",
        ),
        migrations.RenameIndex(
            model_name="possession",
            new_name="possessions_outcome_e83bf8_idx",
            old_name="possessions_outcome_poi_idx",
        ),
        migrations.RenameIndex(
            model_name="possession",
            new_name="possessions_has_pai_305a66_idx",
            old_name="possessions_has_paint_idx",
        ),
        migrations.RenameIndex(
            model_name="possession",
            new_name="possessions_is_offe_920dd9_idx",
            old_name="possessions_is_offens_idx",
        ),
        migrations.RenameIndex(
            model_name="possession",
            new_name="possessions_shoot_q_c2a451_idx",
            old_name="possessions_shoot_qual_idx",
        ),
        migrations.RenameIndex(
            model_name="possession",
            new_name="possessions_after_t_d33576_idx",
            old_name="possessions_after_tim_idx",
        ),
        migrations.RemoveField(
            model_name="possession",
            name="defensive_sequence",
        ),
        migrations.RemoveField(
            model_name="possession",
            name="logged_by",
        ),
        migrations.RemoveField(
            model_name="possession",
            name="offensive_sequence",
        ),
        migrations.AlterField(
            model_name="possession",
            name="duration_seconds",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="possession",
            name="opponent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="defensive_possessions",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="possession",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("MADE_2PTS", "Made 2-Point Shot"),
                    ("MISSED_2PTS", "Missed 2-Point Shot"),
                    ("MADE_3PTS", "Made 3-Point Shot"),
                    ("MISSED_3PTS", "Missed 3-Point Shot"),
                    ("MADE_FTS", "Made Free Throw"),
                    ("MISSED_FTS", "Missed Free Throw"),
                    ("TURNOVER", "Turnover"),
                    ("FOUL", "Foul"),
                    ("REBOUND", "Rebound"),
                    ("STEAL", "Steal"),
                    ("BLOCK", "Block"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="possession",
            name="quarter",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="possession",
            name="start_time_in_game",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="possession",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offensive_possessions",
                to="teams.team",
            ),
        ),
    ]
