# Generated by Django 5.2.5 on 2025-08-17 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('possessions', '0005_alter_possession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='possession',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='possessions', to='games.game'),
            preserve_default=False,
        ),
    ]
