# Generated by Django 5.2.5 on 2025-08-17 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possessions', '0006_possession_game'),
        ('teams', '0003_team_competition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possession',
            name='opponent',
        ),
        migrations.AlterField(
            model_name='possession',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_possessions', to='teams.team'),
        ),
    ]
