# Generated by Django 5.2.5 on 2025-08-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("possessions", "0007_add_sequence_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="possession",
            name="defensive_sequence",
            field=models.TextField(
                blank=True, help_text="Sequence of defensive actions"
            ),
        ),
        migrations.AlterField(
            model_name="possession",
            name="offensive_sequence",
            field=models.TextField(
                blank=True, help_text="Sequence of offensive actions"
            ),
        ),
    ]
