# Generated by Django 5.2.5 on 2025-08-17 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possessions', '0007_remove_possession_opponent_alter_possession_team'),
        ('teams', '0003_team_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='possession',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent_for_possessions', to='teams.team'),
        ),
    ]
