# Generated by Django 5.2.5 on 2025-08-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PRACTICE_TEAM", "Team Practice"),
                            ("PRACTICE_INDIVIDUAL", "Individual Practice"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
    ]
