"""
Django settings for basketball_analytics project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ensure logs directory exists
LOG_DIR = BASE_DIR / "logs"
os.makedirs(LOG_DIR, exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-dtwsg0k&uxi9z6hpr!*2bw8g(92t_ohu=#@&$lc_wb-342p#m("

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "django_filters",
    "drf_spectacular",
    # Our apps
    "apps.core.apps.CoreConfig",
    "apps.users.apps.UsersConfig",
    "apps.teams.apps.TeamsConfig",
    "apps.plays.apps.PlaysConfig",
    "apps.possessions.apps.PossessionsConfig",
    "apps.competitions.apps.CompetitionsConfig",
    "apps.games.apps.GamesConfig",
    "apps.events.apps.EventsConfig",
    "apps.scouting.apps.ScoutingConfig",
    "apps.competition_management.apps.CompetitionManagementConfig",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.gzip.GZipMiddleware",  # Enable GZip compression
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add this line
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Custom logging middlewares
    "basketball_analytics.middleware.ExceptionLoggingMiddleware",
    "basketball_analytics.middleware.RequestLoggingMiddleware",
    "basketball_analytics.middleware.PerformanceMonitoringMiddleware",
]

ROOT_URLCONF = "basketball_analytics.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "basketball_analytics.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration
# Use PostgreSQL for both development and production
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "basketball_analytics"),
        "USER": os.getenv("DB_USER", os.getenv("USER", "postgres")),  # Use current user as default
        "PASSWORD": os.getenv("DB_PASSWORD", ""),  # Empty password for local development
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "OPTIONS": {
            "connect_timeout": 10,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"

# Email settings
# Use custom backend that handles SSL certificate issues
# For development/testing, use console backend to see emails in terminal
EMAIL_BACKEND = "apps.games.email_backend.ConsoleEmailBackend"
# For production with Gmail, use: 'apps.games.email_backend.CustomSMTPEmailBackend'
EMAIL_HOST = "smtp.gmail.com"  # Gmail SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False  # Use TLS, not SSL

# Email credentials - use environment variables for security
import os

EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "your-email@gmail.com")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "your-app-password")
DEFAULT_FROM_EMAIL = f"Basketball Analytics <{EMAIL_HOST_USER}>"

# SSL/TLS settings to handle certificate issues
EMAIL_SSL_CERTFILE = None
EMAIL_SSL_KEYFILE = None
EMAIL_TIMEOUT = 30

# For development, you can use console backend instead
# EMAIL_BACKEND = 'apps.games.email_backend.CustomSMTPEmailBackend'

# Frontend URL for email links
FRONTEND_URL = "http://localhost:8080"

# Add this section at the bottom of the file
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",  # Example for a standard frontend dev server
    "http://127.0.0.1:8080",
    "http://localhost:3000",  # React dev server
    "http://127.0.0.1:3000",
    "http://localhost:5173",  # Vite dev server
    "http://127.0.0.1:5173",
]

CORS_ALLOW_ALL_ORIGINS = True  # For development only

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "origin",
    "x-requested-with",
    "x-csrftoken",
]

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
    "EXCEPTION_HANDLER": "apps.core.exceptions.custom_exception_handler",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
}

# Centralized logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s | %(levelname)s | %(name)s | %(process)d | %(thread)d | %(message)s",
        },
        "concise": {
            "format": "%(levelname)s %(name)s: %(message)s",
        },
        "request": {
            "format": "%(asctime)s | %(levelname)s | %(name)s | method=%(method)s path=%(path)s user=%(user)s status=%(status)s duration_ms=%(duration_ms)s ip=%(ip)s ua=%(ua)s referer=%(referer)s origin=%(origin)s req_id=%(request_id)s",
        },
        "slow_query": {
            "format": "%(asctime)s | %(levelname)s | %(name)s | duration_ms=%(duration_ms)s sql=%(sql)s params=%(params)s",
        },
        "json": {
            "()": "basketball_analytics.logging_formatters.JsonFormatter",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
        "request_console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
        "slow_query_console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
        "request_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "requests.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 3,
            "formatter": "json",
        },
        "app_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "app.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 3,
            "formatter": "json",
        },
        "slow_query_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "slow_queries.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 3,
            "formatter": "json",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "app_file"],
            "level": "WARNING",  # Changed from INFO to WARNING
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console", "app_file"],
            "level": "WARNING",
            "propagate": False,
        },
        "app": {
            "handlers": ["console", "app_file"],
            "level": "WARNING",  # Changed from INFO to WARNING
            "propagate": False,
        },
        "request": {
            "handlers": ["request_console", "request_file"],
            "level": "WARNING",  # Changed from INFO to WARNING
            "propagate": False,
        },
        "db.slow": {
            "handlers": ["slow_query_console", "slow_query_file"],
            "level": "WARNING",  # Changed from INFO to WARNING
            "propagate": False,
        },
    },
}

# Performance monitoring settings
SLOW_QUERY_MS = 100  # tuned threshold
SLOW_REQUEST_MS = 1000  # Log requests taking more than 1 second
MAX_QUERIES_PER_REQUEST = 50  # Log requests with more than 50 queries

# Redis Cache Configuration
# Use Redis for both development and production
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 50,
                "retry_on_timeout": True,
            },
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
        },
        "KEY_PREFIX": "basketball_analytics",
        "TIMEOUT": 300,  # 5 minutes default timeout
    },
    "analytics": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 20,
                "retry_on_timeout": True,
            },
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
        },
        "KEY_PREFIX": "analytics",
        "TIMEOUT": 3600,  # 1 hour for analytics data
    },
    "sessions": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/3",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 30,
                "retry_on_timeout": True,
            },
        },
        "KEY_PREFIX": "sessions",
        "TIMEOUT": 86400,  # 24 hours for sessions
    },
}

# Session configuration
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "sessions"

# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
