# Generated by Django 5.2.5 on 2025-08-12 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Possession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField(auto_now_add=True)),
                ('end_timestamp', models.DateTimeField(blank=True, null=True)),
                ('tracking_data', models.JSONField(blank=True, help_text='Stores detailed events or coordinates for this possession.', null=True)),
                ('outcome', models.CharField(blank=True, help_text='e.g., Made 2pt Shot, Turnover, Defensive Rebound', max_length=100, verbose_name='Outcome')),
                ('play_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_in_possessions', to='plays.playdefinition')),
            ],
        ),
    ]
