# Generated by Django 5.2.5 on 2025-08-17 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('teams', '0003_team_competition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField()),
                ('home_team_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_team_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='teams.team')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='competitions.competition')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='teams.team')),
            ],
            options={
                'ordering': ['-game_date'],
            },
        ),
    ]
