# Generated by Django 5.2.5 on 2025-08-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_date", models.DateTimeField()),
                ("home_team_score", models.PositiveIntegerField(blank=True, null=True)),
                ("away_team_score", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-game_date"],
            },
        ),
    ]
