# Generated by Django 5.2.5 on 2025-08-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_date",
            field=models.DateTimeField(),
        ),
    ]
