# Generated by Django 5.2.5 on 2025-08-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0002_initial"),
        ("games", "0002_initial"),
        ("teams", "0003_team_logo_url"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(("home_team", models.F("away_team")), _negated=True),
                name="home_team_different_from_away_team",
            ),
        ),
    ]
