# Generated by Django 5.2.5 on 2025-08-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Play Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('play_type', models.CharField(choices=[('OFFENSIVE', 'Offensive'), ('DEFENSIVE', 'Defensive')], max_length=50, verbose_name='Play Type')),
                ('diagram_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
