# Generated by Django 5.2.5 on 2025-08-28 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plays", "0001_load_initial_plays"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Play Categories",
            },
        ),
        migrations.CreateModel(
            name="PlayDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Play Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "play_type",
                    models.CharField(
                        choices=[
                            ("OFFENSIVE", "Offensive"),
                            ("DEFENSIVE", "Defensive"),
                        ],
                        max_length=50,
                        verbose_name="Play Type",
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="UI Sub-Category",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal Button"),
                            (
                                "STARTS_POSSESSION",
                                "Starts a New Possession (e.g., START)",
                            ),
                            ("ENDS_POSSESSION", "Ends a Possession (e.g., END)"),
                            (
                                "TRIGGERS_SHOT_RESULT",
                                "Triggers Shot Result (e.g., 2pt, 3pt)",
                            ),
                            ("IS_SHOT_RESULT", "Is a Shot Result (e.g., Made, Miss)"),
                            ("OPENS_TURNOVER_MENU", "Opens Turnover Sub-Menu"),
                            ("OPENS_FT_MENU", "Opens Free Throw Sub-Menu"),
                        ],
                        default="NORMAL",
                        help_text="Defines the button's special behavior in the live tracking UI.",
                        max_length=50,
                        verbose_name="UI Action Type",
                    ),
                ),
                ("diagram_url", models.URLField(blank=True, null=True)),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plays",
                        to="plays.playcategory",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="plays.playdefinition",
                    ),
                ),
            ],
        ),
    ]
