# Generated by Django 5.2.5 on 2025-08-28 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plays", "0002_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playdefinition",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plays",
                to="teams.team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playdefinition",
            unique_together={("name", "team")},
        ),
    ]
