# Generated by Django 5.2.5 on 2025-08-16 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playdefinition',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='plays.playdefinition'),
        ),
    ]
