# Generated by Django 5.2.5 on 2025-08-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plays", "0003_initial"),
    ]

    operations = []
