# Generated by Django 5.2.5 on 2025-08-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plays", "0003_playdefinition_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="playdefinition",
            name="category",
            field=models.CharField(
                choices=[
                    ("OFFENSE", "Offense"),
                    ("OFFENSE_HALF_COURT", "Offense Half Court"),
                    ("DEFENSE", "Defense"),
                    ("PLAYERS", "Players"),
                    ("CONTROL", "Control"),
                    ("OUTCOME", "Outcome"),
                    ("ADVANCE", "Advance"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=50,
                verbose_name="UI Category",
            ),
        ),
        migrations.AddField(
            model_name="playdefinition",
            name="subcategory",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="UI Sub-Category"
            ),
        ),
        migrations.AlterField(
            model_name="playdefinition",
            name="play_type",
            field=models.CharField(
                choices=[
                    ("OFFENSE", "Offense"),
                    ("OFFENSE_HALF_COURT", "Offense Half Court"),
                    ("DEFENSE", "Defense"),
                    ("PLAYERS", "Players"),
                    ("CONTROL", "Control"),
                    ("OUTCOME", "Outcome"),
                    ("ADVANCE", "Advance"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                verbose_name="Play Type",
            ),
        ),
    ]
