# Generated by Django 5.2.5 on 2025-08-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plays", "0004_playdefinition_category_playdefinition_subcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playdefinition",
            name="category",
            field=models.CharField(
                choices=[
                    ("OFFENSE", "Offense"),
                    ("OFFENSE_HALF_COURT", "Offense Half Court"),
                    ("DEFENSE", "Defense"),
                    ("PLAYERS", "Players"),
                    ("CONTROL", "Control"),
                    ("OUTCOME", "Outcome"),
                    ("SHOOT", "Shoot"),
                    ("TAGOFFREB", "TagOffReb"),
                    ("ADVANCED", "Advanced"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=50,
                verbose_name="UI Category",
            ),
        ),
        migrations.AlterField(
            model_name="playdefinition",
            name="play_type",
            field=models.CharField(
                choices=[
                    ("OFFENSE", "Offense"),
                    ("OFFENSE_HALF_COURT", "Offense Half Court"),
                    ("DEFENSE", "Defense"),
                    ("PLAYERS", "Players"),
                    ("CONTROL", "Control"),
                    ("OUTCOME", "Outcome"),
                    ("SHOOT", "Shoot"),
                    ("TAGOFFREB", "TagOffReb"),
                    ("ADVANCED", "Advanced"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                verbose_name="Play Type",
            ),
        ),
    ]
