# Generated by Django 5.2.5 on 2025-08-26 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plays", "0005_alter_playdefinition_category_and_more"),
        ("teams", "0003_team_competition"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Play Categories",
            },
        ),
        migrations.AlterField(
            model_name="playdefinition",
            name="play_type",
            field=models.CharField(choices=[], max_length=50, verbose_name="Play Type"),
        ),
        migrations.AlterField(
            model_name="playdefinition",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plays",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="playdefinition",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plays",
                to="plays.playcategory",
            ),
        ),
    ]
