# Generated by Django 5.2.5 on 2025-08-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plays", "0006_playcategory_alter_playdefinition_play_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playdefinition",
            name="play_type",
            field=models.CharField(
                choices=[("OFFENSIVE", "Offensive"), ("DEFENSIVE", "Defensive")],
                max_length=50,
                verbose_name="Play Type",
            ),
        ),
    ]
